### ISSUE TITLE
Where is the unit test part?

### ISSUE THREAD

**Issue by thomas-tran** [ShawnShiSS/clean-architecture-azure-cosmos-db#1]
This is a very interesting architecture however I think it will be more complete if you can add Unit test and Mock data to the framework.

**Comment by ShawnShiSS** [comment]
Hello Thomas,

I apologize that this took longer for me to look at. Many thanks for the suggestion!

If you look at the master branch now, there is a Unit Test project that has basic tests setup. 

Thanks again for the feedback!

All the best,
Shawn
