### ISSUE TITLE
Deploying to azure Function

### ISSUE THREAD

**Issue by udeaABTE** [ShawnShiSS/clean-architecture-azure-cosmos-db#21]
Hello 

First i would to say that this repo is very interesting.
We need to have a serverless API with access to cosmos, this is very useful to us. 

But when i deployed it to a new azure function, in the azure portal the repo is giving me errors. Did i do something wrong or what could cause this?

In Azure portal under:

1.  "functions" the error is shown: "Azure Functions runtime is unreachable"

1. "Overview" the error is shown: "CleanArchitectureCosmosDB.AzureFunctions: Object reference not set to an instance of an object."

Any idea how to solve this? 

Thanks

**Comment by ShawnShiSS** [comment]
@udeaABTE , this is a tricky one as I am not familiar with your Azure config. What I would suggest to look in your Azure Portal are:

1. Whether your Azure Functions has the proper Application Settings configured, such as connection strings.
1. Look for log files in yourAzureFunctionName.scm.azurewebsites.net. Serilog is configured for logging, you should see log files there.

Good luck!
Shawn
